# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

i=0
flag=0

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(20, 310, 221, 101))
        self.b1.setStyleSheet(" QPushButton#pushButton {\n"
"     background-color: yellow;\n"
" }\n"
" QPushButton#pushButton:pressed {\n"
"     background-color: rgb(224, 0, 0);     \n"
" }\n"
" QPushButton#pushButton:hover {\n"
"     background-color: rgb(224, 255, 0);\n"
" }\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1px solid red;\n"
"}")
        self.b1.setObjectName("b1")





        self.scroll1 = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll1.setGeometry(QtCore.QRect(19, 29, 221, 261))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(18)
        self.scroll1.setFont(font)
        self.scroll1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font color: rgb(0, 255, 0);\n"
"font: 18pt \"8514oem\";")
        self.scroll1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scroll1.setWidgetResizable(True)
        self.scroll1.setObjectName("scroll1")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 219, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll1.setWidget(self.scrollAreaWidgetContents)

        self.fill_scroll()




        self.t1 = QtWidgets.QLabel(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(447, 40, 165, 381))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(18)
        self.t1.setFont(font)
        self.t1.setStyleSheet("background-color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 8px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.t1.setObjectName("t1")



        self.t2 = QtWidgets.QLabel(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(280, 40, 165, 381))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(18)
        self.t2.setFont(font)
        self.t2.setStyleSheet("background-color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 8px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.t2.setObjectName("t2")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionadd = QtWidgets.QAction(MainWindow)
        self.actionadd.setObjectName("actionadd")
        self.actiondelete = QtWidgets.QAction(MainWindow)
        self.actiondelete.setObjectName("actiondelete")
        self.actionpreferences = QtWidgets.QAction(MainWindow)
        self.actionpreferences.setObjectName("actionpreferences")
        self.actiondark_light_theme = QtWidgets.QAction(MainWindow)
        self.actiondark_light_theme.setObjectName("actiondark_light_theme")
        self.menufile.addAction(self.actionadd)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actiondelete)
        self.menuedit.addAction(self.actionpreferences)
        self.menuedit.addSeparator()
        self.menuedit.addAction(self.actiondark_light_theme)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.b1.clicked.connect(lambda: self.event())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b1.setText(_translate("MainWindow", "test"))
        self.scroll1.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#00ff00;\">test</span></p></body></html>"))
        self.t1.setText(_translate("MainWindow", "l1"))
        self.t2.setText(_translate("MainWindow", "l2"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.actionadd.setText(_translate("MainWindow", "add"))
        self.actiondelete.setText(_translate("MainWindow", "delete"))
        self.actionpreferences.setText(_translate("MainWindow", "preferences"))
        self.actiondark_light_theme.setText(_translate("MainWindow", "dark/light theme"))

    def event(self):
        global i
        global flag
        if flag == 0:
            self.t2.setText("PRESSED")
            self.t1.setText(str(i))
            flag = 1
        else:
            self.t2.setText("UNPRESSED")
            self.t1.setText(str(i))
            flag = 0
        i=i+1

    def fill_scroll(self):
        lay = QtWidgets.QVBoxLayout(self.scroll1)

        scrollArea = QtWidgets.QScrollArea()
        lay.addWidget(scrollArea)
        top_widget = QtWidgets.QWidget()
        top_layout = QtWidgets.QVBoxLayout()

        for i in range(10):
            group_box = QtWidgets.QGroupBox()

            layout = QtWidgets.QHBoxLayout(group_box)

            label = QtWidgets.QLabel()
            label.setText('Label For Item {0}'.format(i))
            layout.addWidget(label)

            push_button = QtWidgets.QPushButton(group_box)
            push_button.setText('Run Button')
            push_button.setFixedSize(100, 32)
            layout.addWidget(push_button)

            top_layout.addWidget(group_box)

        top_widget.setLayout(top_layout)
        scrollArea.setWidget(top_widget)





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
